# Welcome to the PhantomEconomy settings file.
# To assist you in its configuration, everything has been accompanied by comments.

# Settings for the default balance system.
default-balance:

  # Should players be given a starting balance for when they first join?
  enabled: true

  # If enabled, this amount will be given to new players.
  amount: 50.00

# Here, you can manage certain aspects of the currency.
currency:

  # There are three currency modes - SYMBOL, WORD and BOTH.
  # SYMBOL: Prefixes the amount with a symbol, such as '$'. e.g. $99.95
  # WORD: Suffixes the amount with a word, such as 'dollars'. e.g. 95.95 dollars
  # BOTH: Uses a combination of the modes above.
  mode: SYMBOL

  # Setting for the SYMBOL mode, only applied if it is enabled above.
  symbol: '$'

  # Settings for the WORD mode, only applied if it is enabled above.
  word:

    # Should a space be inserted between the word and the amount?
    # true: 99.95 dollars
    # false: 99.95dollars
    prefix-space: true

    # When the amount is exactly $1.00.
    singular: 'dollar'

    # When the amount isn't exactly $1.00.
    plural: 'dollars'

# The 'Baltop Update Task Error Repair' is a thing which tries to repair issues when the baltop searches through all of the balances.
# If you are having issues with it, you can turn it off here.
# Expected: [bpolean], Default: [true]
baltop-update-task-error-repair: true

# You can toggle if the baltop update task should run every 10 minutes or not here.
# Disable it if it is causing you issues. If you disable this, then baltop functionality will not be available.
# If you change this setting you must restart your server.
# Expected: [bpolean], Default: [true]
use-baltop-update-task: true

# User-requested addition which allows you to make a task run on startup which updates online player's balances every 10 minutes.
# If you change this setting you must restart your server.
# Expected: [bpolean], Default: [false]
use-balance-update-task: false

# If true, on startup, PE will ask Spigot and tell you if there are any new updates available for the plugin.
updater: true

# This might be useful if I asked you to enable it if you're having issues.
debug: false

# This is the file version.
# It should be unchanged unless updating to the respective version of the settings.yml file.
# Do not increase the number to 'always stay updated', you must use the file version that corresponds to your plugin version.
file-version: 5